var LetterType = [
     {
    	 type:0,
    	 textureName:"hb/inverted_exclamation_mark.png"
     },
     {
    	 type:1,
    	 textureName:"hb/f.png"
     },
     {
    	 type:2,
    	 textureName:"hb/e.png"
     },
     {
    	 type:3,
    	 textureName:"hb/l.png"
     },
     {
    	 type:4,
    	 textureName:"hb/i.png"
     },
     {
    	 type:5,
    	 textureName:"hb/c.png"
     },
     {
    	 type:6,
    	 textureName:"hb/s.png"
     },
     {
    	 type:7,
    	 textureName:""
     },
     {
    	 type:8,
    	 textureName:"hb/3.png"
     },
     {
    	 type:9,
    	 textureName:"hb/1.png"
     },
     {
    	 type:10,
    	 textureName:"hb/exclamation_mark.png"
     }
];